# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'ReactiveObjC', '~> 3.1.1'
target 'RACTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RACTest

  target 'RACTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACTestUITests' do
    # Pods for testing
  end

end
